### ISSUE TITLE
LazyDFU

### ISSUE THREAD

**Issue by Madis0** [Madis0/fabulously-optimized#10]
**Mod name**
LazyDFU

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/lazydfu

**Modrinth link**
N/A

**Other link**
https://github.com/astei/lazydfu

**What it does**
Improves game startup speed

**Why should it be in the modpack**
It makes the boot slightly faster than Smooth Boot

**Why shouldn't it be in the modpack**
Postponing DFU is not ideal, as even stated by the author: https://github.com/astei/lazydfu/issues/2

**Categories**

- [x] Performance optimization
- [ ] Graphics optimization
- [ ] New feature
- [ ] Optifine parity
- [ ] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Additional details**

**Comment by NebelNidas** [comment]
Postponing doesn't make sense, since almost no-one ever uses the "optimize world" feature. End even when someone does, it's better having to wait a bit longer this one time than having additional loading time spent on literally EVERY game start-up

**Comment by NebelNidas** [comment]
Also, it doesn't need to replace SmoothBoot, the two work perfectly fine together, so you get faster start-up times from LazyDFU and the improved responsiveness from SmoothBoot

**Comment by Madis0** [comment]
From the mod page:

> LazyDFU takes a similar implementation approach to Smooth Boot: both mods do not try to modify DFU. However, LazyDFU is superior to Smooth Boot as it does not compile DFU rules at all, which is the most expensive part of the game startup process.

> In comparison, Smooth Boot will instead limit the number of threads that compile DFU rules and run them at a lower priority.

So what would be the benefit of having them together?

**Comment by NebelNidas** [comment]
SmoothBoot is a bit faster than vanilla because it gives the DFU a lower priority. This feature becomes obsolete with LazyDFU, because it prevents the DFU from loading in the first place. But SmoothBoot still has the advantage of introducing better thread- and priority management:
- https://github.com/UltimateBoomer/mc-smoothboot/wiki
- https://github.com/UltimateBoomer/mc-smoothboot/wiki/Configuration~-Fabric-1.16

So, while it might not boost up the game any more than LazyDFU alone, it still makes the game hang less and thus prevents the nasty "Minecraft is not responding" messages on low-end PCs.

**Comment by Madis0** [comment]
Added
