### ISSUE TITLE
Custom client

### ISSUE THREAD

**Issue by TechPro424** [Madis0/fabulously-optimized#101]
### What config to change

Let the modpack be a single jar file.

Optional: split it into 3 jar files: one for Performance, one for Pretty, and one for Functional

So, for example, Sodium, Ferritecore, etc can go into the Performance jar, LambDynamicLights, Fabric Capes can go into the Pretty jar, and WI zoom, AntiGhost can go into the Functional jar

### Why should it be changed

This benefit is for the users of the official launcher, or any other launcher that doesn't support modpacks. Instead of seeing a huge bunch of mods in the mod menu and being somewhat overwhelmed, it can just be a single file called Fabulously Optimized.

Optional: This is for those who just want the Performance aspect of the modpack, or just the Pretty aspect, or just the Functional aspect.

Now I'm a fairly technical person, so I don't mind too much if this is rejected, but I do know people who are not, and am asking this for them (as a lot of them don't even understand how Github works, and therefore are unable to make their own issues).

This might also be useful for others in the community.

### Category

Other

**Comment by Madis0** [comment]
This was already asked once, but fair enough, I'll go into more detail of why this is a bad idea (and out of scope for this project).

* I would need explicit permission from all mods I include
* The authors of the mods would receive no benefits for being included (unless I think of alternative methods like ads and splitting ad money)
* Presumably you want a single settings menu as well, that requires lots of code and maintenance
* Three JARs = 3x maintenance
* Merging mods means they can't be swapped, e.g. if someone prefers Canvas over Sodium or a different zoom mod
* Packaging together would require some kind of script I don't know how to build yet

Now, let's answer the questions you didn't ask.

**Will there be vanilla launcher support?**
Yes, see #88 

**Will there be a consistent settings menu like Optifine?**
Not exactly, but it could come pretty close once Sodium gets a settings API (kind of like Sodium Extra works now).  I have also been considering an alternative settings menu that focuses on things you can change, instead of which mods are included, however I haven't seen an easy and sustainable way to do it yet.

**Will there be separate modpacks for people who only want performance/graphics/functionality?**
No, that's what other modpacks and the open-source nature of this pack is for. Everyone can customize their instance of the pack with whatever they choose to use.

**Comment by TechPro424** [comment]
The main thing I wanted was the consistent settings menu, nice to see it's being considered. Thanks!
