### ISSUE TITLE
ResolutionControl+

### ISSUE THREAD

**Issue by Madis0** [Madis0/fabulously-optimized#20]
**Mod name**
ResolutionControl+

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/resolutioncontrol

**Modrinth link**

**Other link**

**What it does**
Allows changing the scaling of the renderer, taking high-res screenshots

**Why should it be in the modpack**
Optifine parity, faster high-res screenshots than Fabrishot

**Why shouldn't it be in the modpack**
Untested, I think rendering scale = high res screenshot scale (which means using more resources overall, not only when taking screenshots)

**Categories**

- [ ] Performance optimization
- [x] Graphics optimization
- [ ] New feature
- [x] Optifine parity
- [ ] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Additional details**

**Comment by NebelNidas** [comment]
For normal users, it's useless, yeah. But for people with 4K displays (or Retina-Macs), this mod is desperately needed, since you don't need such a high resolution (and Macs often can't handle them), You could of course just lower Minecrafts entire resolution, but this makes the HUD elements blurry. ResolutionControl+ takes the perfect middle ground and only lowers the render resolution, not the UI one.

But I agree, it's not worth it bundling an extra mod that only a small fraction of users will ever use - I would add a notice to the modpack site with an according description for Mac users and just link to the mod.

**Comment by Rajbir98** [comment]
Yes Its Confusing for me

**Comment by Madis0** [comment]
Pros and cons by @Jukitsu:

> **What it does**
This mod allows the player to modify the rendering resolution, and can achieve a nice SuperSampling Anti aliasing effect on a Render quality x2, similar to Optifine's render quality setting in shaders

> **Why should it be in the modpack**
This mod should belong to the pretty section of the modpack, as it allows you to have some sort of antialiasing, which some people might like it.

> **Why shouldn't it be in the modpack**
The mod doesn't supports Fabulous Graphics and it is highly possible it is incompatible with other mods. I haven't been able to test it yet.

Good points, but the question about the target audience still remains - will people know how to use it in the most efficient way for their system? It is not really something I can configure for everyone, it has to be discovered and taken advantage of individually.

Also, Mac point is now moot since Sodium Extra has a simple toggle for that.
