### ISSUE TITLE
No Annoying Settings

### ISSUE THREAD

**Issue by andytxr** [Madis0/fabulously-optimized#29]
No Annoying Settings

[](https://www.curseforge.com/minecraft/mc-mods/no-annoying-settings/)

https://github.com/Luligabi1/NoAnnoyingSettings

This is a very simple, client-side only mod that will automatically disable auto-jump and Minecraft's Music every game restart. This is mostly targeted for modpacks and users of the vanilla launcher, as it erases your previous settings if you open an older version of Minecraft, but most likely can be used by anyone without any incompatibilities. If for any reason you want only one of the two to be disabled, you can use the config located at

If the user makes use of the Vanilla Minecraft Launcher, everytime they launch an older version of Minecraft, their options.txt file will be reset, creating annoyance with some of the questionable default settings minecraft uses. This mod slightly reduces this annoyance by ensuring every start that the music and auto-jump will always be turned off.

- [ ] Performance optimization
- [ ] Graphics optimization
- [X] New feature
- [ ] Optifine parity
- [X] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Comment by Madis0** [comment]
Hmm. 
Judging by the description, it forces these two values at all times, which is a definite no, I'd rather do just a default `options.txt` or #25 instead.

Then comes the question of what options to change though, autojump may be disliked by many, but why music? What about GUI scale? Starting tutorial?

Since I aim for a vanilla-like experience, I must be very careful with the defaults I choose, they should be familiar enough for many people.

**Comment by Madis0** [comment]
Continue in #30
