### ISSUE TITLE
LambdaBetterGrass

### ISSUE THREAD

**Issue by Madis0** [Madis0/fabulously-optimized#6]
**Mod name**
LambdaBetterGrass

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/lambdabettergrass

**Modrinth link**
https://modrinth.com/mod/lambdabettergrass

**Other link**
https://github.com/LambdAurora/LambdaBetterGrass

**What it does**
Adds "better grass" like Optifine

**Why should it be in the modpack**
Optifine parity

**Why shouldn't it be in the modpack**
Rendering API missing

**Categories**

- [ ] Performance optimization
- [x] Graphics optimization
- [ ] New feature
- [x] Optifine parity
- [ ] Fixes a bug/dependency

**Additional details**

Issue I'd like to get fixed first: https://github.com/LambdAurora/LambdaBetterGrass/issues/16

**Comment by MulverineX** [comment]
1.16 & 1.17 work. See above mention in the Indium issue for proof. 

LambdAurora/LambdaBetterGrass#16 can be worked around by providing a default config disabling corner blending because it is optional.
![image](https://user-images.githubusercontent.com/12068027/124193317-da1f7e00-da83-11eb-9e9d-4347f01c601d.png)
