### ISSUE TITLE
Discord server

### ISSUE THREAD

**Issue by TechPro424** [Madis0/fabulously-optimized#83]
Please make a Discord server, for easier support and also for the FO community to interact with and help out each other.

**Comment by Madis0** [comment]
It has once been suggested already, but I've avoided it so far because I don't know if I have the time and patience at the moment to keep up with everyone's ideas, problems and questions, should it become popular. However, if I there are any volunteer moderators for it - let's say, three at least - I could consider it again.

**Comment by TechPro424** [comment]
Maybe make a poll or something? (Google Forms, etc.) and see what others think?

**Comment by Madis0** [comment]
Well, I don't want a poll because the question is not about _what people think_, but _are there people to help others out_. Similarly I don't want moderation applications at the moment, I'd rather pick someone who has already contributed in some way (e.g. if someone has done great suggestions and is willing to volunteer).

**Comment by wafflecoffee** [comment]
I've been following this suggestion for a bit and have decided not to get myself involved until now:
I like the idea of a Discord server. I was waiting for someone else to pipe up in regards to the
> I'd rather pick someone who has already contributed in some way

comment, but nobody else did, so this just serves as me saying I'd be willing to throw my hat in the ring. I don't know if my contributions count as significant enough, but I'm just putting it out there anyways :P

**Comment by Madis0** [comment]
> I've been following this suggestion for a bit and have decided not to get myself involved until now:
> I like the idea of a Discord server. I was waiting for someone else to pipe up in regards to the
> 
> > I'd rather pick someone who has already contributed in some way
> 
> comment, but nobody else did, so this just serves as me saying I'd be willing to throw my hat in the ring in regards to volunteering. I don't know if my contributions count as significant enough, but I'm just putting it out there anyways :P

I appreciate that, and yes, you qualify :grin: 
Join me on https://discord.gg/kMBcfxQx

**Comment by Madis0** [comment]
https://discord.gg/yxaXtaQqdB
