### ISSUE TITLE
Remove anti-ghost

### ISSUE THREAD

**Issue by basedAF** [Madis0/fabulously-optimized#95]
### Describe the bug

Antighost plugin can cause players to get banned on servers.

### Expected behavior

Anti-ghost to not ban me from servers.

### Observed/actual behavior

Pressing G sends hundreds of block dig packets around the player, which will set off anticheat block/nuker checks, by pressing g rather quickly you can get banned on many servers.

### Steps To Reproduce

Use antighost
Get banned

### Modpack version

Latest

### Launcher

Minecraft Launcher (vanilla)

### Install method

Fresh install/new profile

**Comment by Madis0** [comment]
Well, if you hold it down then yes, it could do theoretically do that. However, I have only seen a kick on popular servers, could you name an example that would treat it worse?

**Comment by TheMadHau5** [comment]
I suggest leaving the keybind enabled, but to a far-off key, to prevent accidental presses. That seems like a good compromise to me.

**Comment by Madis0** [comment]
@TheMadHau5 Maybe, but I don't know a key that would make sense and be compatible with every keyboard layout. E.g. F-keys seem suitable but that makes things harder for Mac users and laptop users that need to hold Fn first.

So in the end it seems better to "confirm" the feature by typing it out + being able to find out it exists in the first place (as it is shown on autocomplete) instead of having a random key people may accidentally hit/hold or not even know about.
